CREATE OR REPLACE VIEW PLATFORM.MONITORING.VW_RECENT_QUERY_HISTORY AS
SELECT
  Q.QUERY_ID,
  Q.USER_NAME,
  Q.ROLE_NAME,
  Q.WAREHOUSE_NAME,
  Q.DATABASE_NAME,
  Q.SCHEMA_NAME,
  Q.START_TIME,
  Q.END_TIME,
  Q.TOTAL_ELAPSED_TIME,
  Q.CREDITS_USED_CLOUD_SERVICES,
  Q.QUERY_TEXT
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY Q
WHERE Q.START_TIME >= DATEADD(DAY, -7, CURRENT_TIMESTAMP());