CREATE OR REPLACE VIEW PLATFORM.MONITORING.VW_RECENT_WAREHOUSE_USAGE AS
SELECT
  W.WAREHOUSE_NAME,
  W.START_TIME,
  W.END_TIME,
  W.CREDITS_USED,
  W.CREDITS_USED_COMPUTE,
  W.CREDITS_USED_CLOUD_SERVICES
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY W
WHERE W.START_TIME >= DATEADD(DAY, -7, CURRENT_TIMESTAMP());