!set variable_substitution=true;

-- Target context = SILVER/SALES for the current ENV (DEV/QA/PROD)
USE DATABASE &{ENV}_SILVER;
USE SCHEMA SALES;

CREATE OR REPLACE TABLE FACT_FULFILLMENT (
  ORDER_ID               NUMBER        PRIMARY KEY COMMENT 'Order-Level Fulfillment Record',
  CUSTOMER_ID            NUMBER        COMMENT 'Customer ID',
  ORDER_DATE_ID          NUMBER        COMMENT 'YYYYMMDD from CREATED_AT',
  SHIPPED_DATE_ID        NUMBER        COMMENT 'YYYYMMDD fron SHIPPED_AT',
  DELIVERED_DATE_ID      NUMBER        COMMENT 'YYYYMMDD from DELIVERED_AT',
  FULFILLMENT_STATUS     STRING        COMMENT 'Derived from ORDER STATUS/TIMESTAMPS',
  CREATED_TO_SHIP_DAYS   NUMBER        COMMENT 'DATEDIFF CREATED_AT→SHIPPED_AT',
  SHIP_TO_DELIVER_DAYS   NUMBER        COMMENT 'DATEDIFF SHIPPED_AT→DELIVERED_AT',
  CREATED_TO_DELIVER_DAYS NUMBER       COMMENT 'DATEDIFF CREATED_AT→DELIVERED_AT'
)
COMMENT='It stores information about Fullflment / Shipping Performance of the orders';

INSERT INTO FACT_FULFILLMENT (
  ORDER_ID, CUSTOMER_ID,
  ORDER_DATE_ID, SHIPPED_DATE_ID, DELIVERED_DATE_ID,
  FULFILLMENT_STATUS,
  CREATED_TO_SHIP_DAYS, SHIP_TO_DELIVER_DAYS, CREATED_TO_DELIVER_DAYS
)
SELECT
  O.ORDER_ID,
  O.CUSTOMER_ID,
  TO_NUMBER(TO_CHAR(O.CREATED_AT::DATE,   'YYYYMMDD'))                                                    AS ORDER_DATE_ID,
  IFF(O.SHIPPED_AT   IS NULL, NULL, TO_NUMBER(TO_CHAR(O.SHIPPED_AT::DATE,   'YYYYMMDD')))                 AS SHIPPED_DATE_ID,
  IFF(O.DELIVERED_AT IS NULL, NULL, TO_NUMBER(TO_CHAR(O.DELIVERED_AT::DATE, 'YYYYMMDD')))                 AS DELIVERED_DATE_ID,
  CASE
    WHEN O.DELIVERED_AT IS NOT NULL THEN 'DELIVERED'
    WHEN O.SHIPPED_AT   IS NOT NULL THEN 'SHIPPED'
    WHEN O.CREATED_AT   IS NOT NULL THEN 'PENDING_SHIPMENT'
    ELSE 'UNKNOWN'
  END                                                                                                     AS FULFILLMENT_STATUS,
  IFF(O.SHIPPED_AT   IS NULL, NULL, DATEDIFF('DAY', O.CREATED_AT,  O.SHIPPED_AT))                         AS CREATED_TO_SHIP_DAYS,
  IFF(O.DELIVERED_AT IS NULL OR O.SHIPPED_AT IS NULL, NULL, DATEDIFF('DAY', O.SHIPPED_AT, O.DELIVERED_AT)) AS SHIP_TO_DELIVER_DAYS,
  IFF(O.DELIVERED_AT IS NULL, NULL, DATEDIFF('DAY', O.CREATED_AT,  O.DELIVERED_AT))                       AS CREATED_TO_DELIVER_DAYS
FROM &{ENV}_SILVER.STAGING.ORDERS O;
