!set variable_substitution=true;

-- Target context = SILVER/SALES for the current ENV (DEV/QA/PROD)
USE DATABASE &{ENV}_SILVER;
USE SCHEMA SALES;

CREATE OR REPLACE TABLE FACT_FULFILLMENT (
  ORDER_ID               NUMBER        PRIMARY KEY COMMENT 'Order-Level Fulfillment Record',
  CUSTOMER_ID            NUMBER        COMMENT 'Customer ID',
  ORDER_DATE_ID          NUMBER        COMMENT 'YYYYMMDD from CREATED_AT',
  SHIPPED_DATE_ID        NUMBER        COMMENT 'YYYYMMDD fron SHIPPED_AT',
  DELIVERED_DATE_ID      NUMBER        COMMENT 'YYYYMMDD from DELIVERED_AT',
  FULFILLMENT_STATUS     STRING        COMMENT 'Derived from ORDER STATUS/TIMESTAMPS',
  CREATED_TO_SHIP_DAYS   NUMBER        COMMENT 'DATEDIFF CREATED_AT→SHIPPED_AT',
  SHIP_TO_DELIVER_DAYS   NUMBER        COMMENT 'DATEDIFF SHIPPED_AT→DELIVERED_AT',
  CREATED_TO_DELIVER_DAYS NUMBER       COMMENT 'DATEDIFF CREATED_AT→DELIVERED_AT',
    -- Data Quality Flags (1 = bad chronology)
  QF_SHIP_BEFORE_CREATE    NUMBER        COMMENT '1 IF SHIPPED_AT < CREATED_AT',
  QF_DELIVER_BEFORE_SHIP   NUMBER        COMMENT '1 IF DELIVERED_AT < SHIPPED_AT',
  QF_DELIVER_BEFORE_CREATE NUMBER        COMMENT '1 IF DELIVERED_AT < CREATED_AT'
)
COMMENT='It stores information about Fulfillment/ Shipping performance of the orders';

INSERT INTO FACT_FULFILLMENT (
  ORDER_ID, CUSTOMER_ID,
  ORDER_DATE_ID, SHIPPED_DATE_ID, DELIVERED_DATE_ID,
  FULFILLMENT_STATUS,
  CREATED_TO_SHIP_DAYS, SHIP_TO_DELIVER_DAYS, CREATED_TO_DELIVER_DAYS,
  QF_SHIP_BEFORE_CREATE, QF_DELIVER_BEFORE_SHIP, QF_DELIVER_BEFORE_CREATE
)
WITH S AS (
  SELECT
    O.ORDER_ID,
    O.CUSTOMER_ID,
    O.CREATED_AT,
    O.SHIPPED_AT,
    O.DELIVERED_AT,
    O.STATUS,

    /* Chronology checks (TRUE when bad) */
    (O.SHIPPED_AT   < O.CREATED_AT)   AS BAD_SHIP_BEFORE_CREATE,
    (O.DELIVERED_AT < O.SHIPPED_AT)   AS BAD_DELIVER_BEFORE_SHIP,
    (O.DELIVERED_AT < O.CREATED_AT)   AS BAD_DELIVER_BEFORE_CREATE
  FROM &{ENV}_SILVER.STAGING.ORDER_ITEMS O
)
SELECT
  ORDER_ID,
  CUSTOMER_ID,
  TO_NUMBER(TO_CHAR(CREATED_AT::DATE,   'YYYYMMDD'))                                       AS ORDER_DATE_ID,
  IFF(SHIPPED_AT   IS NULL, NULL, TO_NUMBER(TO_CHAR(SHIPPED_AT::DATE,   'YYYYMMDD')))      AS SHIPPED_DATE_ID,
  IFF(DELIVERED_AT IS NULL, NULL, TO_NUMBER(TO_CHAR(DELIVERED_AT::DATE, 'YYYYMMDD')))      AS DELIVERED_DATE_ID,
  STATUS                                                                                   AS FULFILLMENT_STATUS,

  /* Latencies: NULL if chronology is invalid */
  IFF(SHIPPED_AT IS NULL OR BAD_SHIP_BEFORE_CREATE,NULL, DATEDIFF('DAY', CREATED_AT, SHIPPED_AT))  AS CREATED_TO_SHIP_DAYS,
  IFF(DELIVERED_AT IS NULL OR SHIPPED_AT IS NULL OR BAD_DELIVER_BEFORE_SHIP,NULL, DATEDIFF('DAY', SHIPPED_AT, DELIVERED_AT))   AS SHIP_TO_DELIVER_DAYS,
  IFF(DELIVERED_AT IS NULL OR BAD_DELIVER_BEFORE_CREATE,NULL, DATEDIFF('DAY', CREATED_AT, DELIVERED_AT))  AS CREATED_TO_DELIVER_DAYS,

  /* Quality flags: 1 = bad chronology */
  IFF(BAD_SHIP_BEFORE_CREATE,   1, 0)      AS QF_SHIP_BEFORE_CREATE,
  IFF(BAD_DELIVER_BEFORE_SHIP,  1, 0)      AS QF_DELIVER_BEFORE_SHIP,
  IFF(BAD_DELIVER_BEFORE_CREATE,1, 0)      AS QF_DELIVER_BEFORE_CREATE
FROM S;
