!set variable_substitution=true;

-- Target context = SILVER/MARKETING for the current ENV (DEV/QA/PROD)
USE DATABASE &{ENV}_SILVER;
USE SCHEMA FINANCE;


-- Change this if your fiscal year starts in another month (1=Jan, 2=Feb, 4=Apr, etc.)
SET FISCAL_START_MONTH = 1;

CREATE OR REPLACE TABLE DIM_FISCAL_CALENDAR AS
WITH D AS (
  SELECT
    DATE_ID,
    FULL_DATE,
    YEAR_NUM,
    MONTH_NUM,
    QUARTER_NUM
  FROM &{ENV}_SILVER.COMMON.DIM_DATE
),
SHIFTED AS (
  SELECT
    DATE_ID,
    FULL_DATE,
    DATEADD(MONTH, -($FISCAL_START_MONTH - 1), FULL_DATE) AS SHIFTED_DATE
  FROM D
)
SELECT
  DATE_ID,
  FULL_DATE,
  YEAR(SHIFTED_DATE)                                         AS FISCAL_YEAR,
  MONTH(SHIFTED_DATE)                                        AS FISCAL_MONTH_NUM,
  CEIL(MONTH(SHIFTED_DATE) / 3.0)                            AS FISCAL_QUARTER_NUM,
  TO_CHAR(SHIFTED_DATE, 'MON')                               AS FISCAL_MONTH_NAME,
  'FY' || TO_CHAR(YEAR(SHIFTED_DATE))                        AS FISCAL_YEAR_LABEL,
  'FQ' || CEIL(MONTH(SHIFTED_DATE) / 3.0)                    AS FISCAL_QTR_LABEL
FROM SHIFTED;


-- Added TABLE COMMENT
ALTER TABLE DIM_FISCAL_CALENDAR SET COMMENT = 'Fiscal calendar derived from DIM_DATE; supports reporting by fiscal year/quarter/month.';

-- Added COLUMN COMMENTS
ALTER TABLE DIM_FISCAL_CALENDAR MODIFY COLUMN DATE_ID COMMENT 'YYYYMMDD surrogate key from DIM_DATE.FULL_DATE';
ALTER TABLE DIM_FISCAL_CALENDAR MODIFY COLUMN FULL_DATE COMMENT 'Calendar date (DATE)';
ALTER TABLE DIM_FISCAL_CALENDAR MODIFY COLUMN FISCAL_YEAR COMMENT 'Fiscal year number based on configured start month';
ALTER TABLE DIM_FISCAL_CALENDAR MODIFY COLUMN FISCAL_MONTH_NUM COMMENT 'Fiscal month number (1–12) within fiscal year';
ALTER TABLE DIM_FISCAL_CALENDAR MODIFY COLUMN FISCAL_QUARTER_NUM COMMENT 'Fiscal quarter number (1–4) within fiscal year';
ALTER TABLE DIM_FISCAL_CALENDAR MODIFY COLUMN FISCAL_MONTH_NAME COMMENT 'Fiscal month short name (e.g., JAN, FEB)';
ALTER TABLE DIM_FISCAL_CALENDAR MODIFY COLUMN FISCAL_YEAR_LABEL COMMENT 'Label like FY2025';
ALTER TABLE DIM_FISCAL_CALENDAR MODIFY COLUMN FISCAL_QTR_LABEL COMMENT 'Label like FQ3';

