!set variable_substitution=true;

-- Target context = SILVER/MARKETING for the current ENV (DEV/QA/PROD)
USE DATABASE &{ENV}_SILVER;
USE SCHEMA FINANCE;

CREATE OR REPLACE TABLE FACT_COGS_DAILY AS
WITH COGS_D AS (
  SELECT
    ORDER_DATE_ID AS DATE_ID,
    SUM(COALESCE(UNIT_COST_AT_SALE, 0) * COALESCE(QUANTITY, 1)) AS COGS
  FROM &{ENV}_SILVER.SALES.FACT_ORDER_ITEMS
  GROUP BY ORDER_DATE_ID
),
COGS_REVERSAL_D AS (
  -- assume the unit cost at sale approximates the cost to reverse on return
  SELECT
    R.RETURN_DATE_ID AS DATE_ID,
    SUM(COALESCE(I.UNIT_COST_AT_SALE, 0) * COALESCE(I.QUANTITY, 1)) AS COGS_RETURN_REVERSAL
  FROM &{ENV}_SILVER.SALES.FACT_RETURNS R
  JOIN &{ENV}_SILVER.SALES.FACT_ORDER_ITEMS I
    ON I.ORDER_ITEM_ID = R.ORDER_ITEM_ID
  GROUP BY R.RETURN_DATE_ID
)
SELECT
  COALESCE(C.DATE_ID, X.DATE_ID)                                     AS DATE_ID,
  COALESCE(C.COGS, 0)                                                AS COGS,
  COALESCE(X.COGS_RETURN_REVERSAL, 0)                                AS COGS_RETURN_REVERSAL,
  COALESCE(C.COGS, 0) - COALESCE(X.COGS_RETURN_REVERSAL, 0)          AS NET_COGS
FROM COGS_D C
FULL OUTER JOIN COGS_REVERSAL_D X
  ON C.DATE_ID = X.DATE_ID;

-- COMMENTS: FACT_COGS_DAILY
ALTER TABLE FACT_COGS_DAILY SET COMMENT = 'It stores daily COGS rollup: item cost at sale minus cost reversals on the return date.';

ALTER TABLE FACT_COGS_DAILY MODIFY COLUMN DATE_ID COMMENT 'YYYYMMDD date key for daily aggregation (join to DIM_DATE / DIM_FISCAL_CALENDAR)';
ALTER TABLE FACT_COGS_DAILY MODIFY COLUMN COGS COMMENT 'Sum of UNIT_COST_AT_SALE * QUANTITY grouped by ORDER_DATE_ID';
ALTER TABLE FACT_COGS_DAILY MODIFY COLUMN COGS_RETURN_REVERSAL COMMENT 'Cost reversals from returns grouped by RETURN_DATE_ID';
ALTER TABLE FACT_COGS_DAILY ALTER COLUMN NET_COGS COMMENT 'COGS minus COGS_RETURN_REVERSAL';
