!set variable_substitution=true;

-- Target context = GOLD/ANALYTICS for the current ENV (DEV/QA/PROD)
USE DATABASE &{ENV}_GOLD;
USE SCHEMA ANALYTICS;

-- Purpose: Daily revenue/COGS with calendar + fiscal labels

CREATE OR REPLACE VIEW VW_PNL_DAILY AS
WITH R AS (
  SELECT DATE_ID, GROSS_REVENUE, REFUNDS, NET_REVENUE
  FROM &{ENV}_SILVER.FINANCE.FACT_REVENUE_DAILY
),
C AS (
  SELECT DATE_ID, COGS, COGS_RETURN_REVERSAL, NET_COGS
  FROM &{ENV}_SILVER.FINANCE.FACT_COGS_DAILY
),
D AS (
  SELECT DATE_ID, FULL_DATE, YEAR_NUM, MONTH_NUM, QUARTER_NUM
  FROM &{ENV}_SILVER.COMMON.DIM_DATE
),
F AS (
  SELECT DATE_ID, FISCAL_YEAR, FISCAL_QUARTER_NUM, FISCAL_MONTH_NUM,
         FISCAL_YEAR_LABEL, FISCAL_QTR_LABEL, FISCAL_MONTH_NAME
  FROM &{ENV}_SILVER.FINANCE.DIM_FISCAL_CALENDAR
)
SELECT
  COALESCE(R.DATE_ID, C.DATE_ID)   AS DATE_ID,
  D.FULL_DATE,
  D.YEAR_NUM,
  D.QUARTER_NUM,
  D.MONTH_NUM,
  F.FISCAL_YEAR,
  F.FISCAL_QUARTER_NUM,
  F.FISCAL_MONTH_NUM,
  F.FISCAL_YEAR_LABEL,
  F.FISCAL_QTR_LABEL,
  F.FISCAL_MONTH_NAME,
  COALESCE(R.GROSS_REVENUE, 0)                                     AS GROSS_REVENUE,
  COALESCE(R.REFUNDS, 0)                                           AS REFUNDS,
  COALESCE(C.COGS, 0)                                              AS COGS,
  COALESCE(C.COGS_RETURN_REVERSAL, 0)                              AS COGS_RETURN_REVERSAL,
  COALESCE(R.GROSS_REVENUE, 0) - COALESCE(C.COGS, 0)               AS GROSS_MARGIN,
  COALESCE(R.NET_REVENUE, 0) - COALESCE(C.NET_COGS, 0)             AS NET_GROSS_MARGIN
FROM R
FULL OUTER JOIN C ON R.DATE_ID = C.DATE_ID
LEFT JOIN D ON D.DATE_ID = COALESCE(R.DATE_ID, C.DATE_ID)
LEFT JOIN F ON F.DATE_ID = COALESCE(R.DATE_ID, C.DATE_ID);

-- Notes:
-- - Join to both calendar and fiscal dims so consumers can slice either way.
-- - GROSS_MARGIN uses gross values; NET_GROSS_MARGIN uses net values (after refunds/return reversals).