CREATE TABLE IF NOT EXISTS DEV_BRONZE.RAW.ORDERS (
  ORDER_ID     NUMBER,
  USER_ID      NUMBER,
  STATUS       VARCHAR,
  GENDER       VARCHAR,
  CREATED_AT   TIMESTAMP_NTZ,
  RETURNED_AT  TIMESTAMP_NTZ,
  SHIPPED_AT   TIMESTAMP_NTZ,
  DELIVERED_AT TIMESTAMP_NTZ,
  NUM_OF_ITEM  NUMBER(18,0)
);

CREATE TABLE IF NOT EXISTS DEV_BRONZE.RAW.ORDER_ITEMS (
  ID              NUMBER,
  ORDER_ID        NUMBER,
  USER_ID         NUMBER,
  PRODUCT_ID      NUMBER,
  INVENTORY_ITEM  NUMBER,
  STATUS          VARCHAR,
  CREATED_AT      TIMESTAMP_NTZ,
  SHIPPED_AT      TIMESTAMP_NTZ,
  DELIVERED_AT    TIMESTAMP_NTZ,
  RETURNED_AT     TIMESTAMP_NTZ,
  SALES_PRICE     NUMBER(18,2)
);

CREATE TABLE IF NOT EXISTS DEV_BRONZE.RAW.USERS (
  ID               NUMBER,
  FIRST_NAME       VARCHAR,
  LAST_NAME        VARCHAR,
  EMAIL            VARCHAR,
  AGE              NUMBER(9,0),
  GENDER           VARCHAR,
  STATE            VARCHAR,
  STREET_ADDRESS   VARCHAR,
  POSTAL_CODE      VARCHAR,
  CITY             VARCHAR,
  COUNTRY          VARCHAR,
  LATITUDE         FLOAT,
  LONGITUDE        FLOAT,
  TRAFFIC_SOURCE   VARCHAR,
  CREATED_AT       TIMESTAMP_NTZ,
  USER_GEOM        VARCHAR
);

CREATE TABLE IF NOT EXISTS DEV_BRONZE.RAW.EVENTS (
  ID             NUMBER,
  USER_ID        NUMBER,
  SEQUENCE       NUMBER(18,0),
  SESSION_ID     VARCHAR,
  CREATED_AT     TIMESTAMP_NTZ,
  IP_ADDRESS     VARCHAR,
  CITY           VARCHAR,
  STATE          VARCHAR,
  POSTAL_CODE    VARCHAR,
  BROWSER        VARCHAR,
  TRAFFIC_SOURCE VARCHAR,
  URI            VARCHAR,
  EVENT_TYPE     VARCHAR
);

CREATE TABLE IF NOT EXISTS DEV_BRONZE.RAW.PRODUCTS (
  ID                     NUMBER,
  COST                   NUMBER(18,2),
  CATEGORY               VARCHAR,
  NAME                   VARCHAR,
  BRAND                  VARCHAR,
  RETAIL_PRICE           NUMBER(18,2),
  DEPARTMENT             VARCHAR,
  SKU                    VARCHAR,
  DISTRIBUTION_CENTER_ID NUMBER
);

CREATE TABLE IF NOT EXISTS DEV_BRONZE.RAW.DISTRIBUTION_CENTERS (
  ID                      NUMBER,
  NAME                    VARCHAR,
  LATTITUDE               FLOAT,
  LONGITUDE               FLOAT,
  DISTRIBUTION_CENTER_GEOM VARCHAR
);

CREATE TABLE IF NOT EXISTS DEV_BRONZE.RAW.INVENTORY_ITEMS (
  ID                    NUMBER,
  PRODUCT_ID            NUMBER,
  CREATED_AT            TIMESTAMP_NTZ,
  SOLD_AT               TIMESTAMP_NTZ,
  COST                  NUMBER(18,2),
  PRODUCT_CATEGORY      VARCHAR,
  PRODUCT_NAME          VARCHAR,
  PRODUCT_BRAND         VARCHAR,
  PRODUCT_RETAIL_PRICE  NUMBER(18,2),
  PRODUCT_DEPARTMENT    VARCHAR,
  PRODUCT_SKU           VARCHAR,
  PRODUCT_ID_DUP        NUMBER 
);