!set variable_substitution=true;

-- Target context = SILVER/MARKETING for the current ENV (DEV/QA/PROD)
USE DATABASE &{ENV}_SILVER;
USE SCHEMA MARKETING;

CREATE OR REPLACE TABLE DIM_EVENT_TYPE (
  EVENT_TYPE_ID   NUMBER AUTOINCREMENT PRIMARY KEY COMMENT 'Surrogate key of the event',
  EVENT_TYPE_NAME STRING NOT NULL COMMENT 'It stores RAW/CONFORMED event type name',
  DESCRIPTION     STRING COMMENT 'Optional Freeform Description'
)
COMMENT='It stores list of distinct event types that happens in the system';

INSERT INTO DIM_EVENT_TYPE (EVENT_TYPE_NAME, DESCRIPTION)
SELECT DISTINCT
  UPPER(TRIM(EVENT_TYPE))   AS EVENT_TYPE_NAME,
  NULL                      AS DESCRIPTION
FROM &{ENV}_SILVER.STAGING.EVENTS
WHERE EVENT_TYPE IS NOT NULL;
