!set variable_substitution=true;

-- Target context = SILVER/MARKETING for the current ENV (DEV/QA/PROD)
USE DATABASE &{ENV}_SILVER;
USE SCHEMA MARKETING;

CREATE OR REPLACE TABLE FACT_EVENTS (
  EVENT_ID        NUMBER        PRIMARY KEY COMMENT 'It stores Business key from STAGING.EVENTS',
  SESSION_ID      STRING        COMMENT 'It store the SESSION ID',
  CUSTOMER_ID     NUMBER        COMMENT 'It store the CUSTOMER ID',
  EVENT_TYPE_ID   NUMBER        COMMENT 'FK TO DIM_EVENT_TYPE',
  EVENT_DATE_ID   NUMBER        COMMENT 'YYYYMMDD FROM CREATED_AT',
  SEQUENCE        NUMBER        COMMENT 'Order within Session',
  URI             STRING        COMMENT 'It stores Page/resource',
  BROWSER         STRING        COMMENT 'it stores name of the BROWSER from EVENT',
  CHANNEL_ID      NUMBER        COMMENT 'FK TO DIM_CHANNEL (VIA TRAFFIC_SOURCE)',
  GEO_ID          NUMBER        COMMENT 'FK TO DIM_GEOGRAPHY (OPTIONAL MATCH ON CITY/STATE/POSTAL)'
)
COMMENT=' It stores information about single customer action in a session.';

INSERT OVERWRITE INTO FACT_EVENTS (
  EVENT_ID, SESSION_ID, CUSTOMER_ID, EVENT_TYPE_ID, EVENT_DATE_ID,
  SEQUENCE, URI, BROWSER, CHANNEL_ID, GEO_ID
)
WITH E AS (
  SELECT
    EVENT_ID,
    SESSION_ID,
    CUSTOMER_ID,
    UPPER(TRIM(EVENT_TYPE)) AS EVENT_TYPE_NAME,
    CREATED_AT,
    SEQUENCE,
    URI,
    BROWSER,
    TRAFFIC_SOURCE,
    CITY, STATE, POSTAL_CODE
  FROM &{ENV}_SILVER.STAGING.EVENTS
),
ET AS (  -- EVENT TYPE KEY
  SELECT EVENT_TYPE_ID, EVENT_TYPE_NAME
  FROM &{ENV}_SILVER.MARKETING.DIM_EVENT_TYPE
),
CH AS (  -- CHANNEL KEY
  SELECT CHANNEL_ID, RAW_SOURCE
  FROM &{ENV}_SILVER.COMMON.DIM_CHANNEL
),
G AS (   -- OPTIONAL GEO KEY (MATCH ON CITY/STATE/POSTAL)
  SELECT GEO_ID, CITY, STATE, POSTAL_CODE
  FROM &{ENV}_SILVER.COMMON.DIM_GEOGRAPHY
)
SELECT
  E.EVENT_ID,
  E.SESSION_ID,
  E.CUSTOMER_ID,
  ET.EVENT_TYPE_ID,
  TO_NUMBER(TO_CHAR(E.CREATED_AT::DATE,'YYYYMMDD')) AS EVENT_DATE_ID,
  E.SEQUENCE,
  E.URI,
  E.BROWSER,
  CH.CHANNEL_ID,
  G.GEO_ID
FROM E
LEFT JOIN ET
  ON ET.EVENT_TYPE_NAME = E.EVENT_TYPE_NAME
LEFT JOIN CH
  ON UPPER(CH.RAW_SOURCE) = UPPER(E.TRAFFIC_SOURCE)
LEFT JOIN G
  ON NVL(G.CITY,'') = NVL(E.CITY,'')
 AND NVL(G.STATE,'') = NVL(E.STATE,'')
 AND NVL(G.POSTAL_CODE,'') = NVL(E.POSTAL_CODE,'');
