!set variable_substitution=true;

-- Target context = SILVER/COMMON for the current ENV (DEV/QA/PROD)
USE DATABASE &{ENV}_SILVER;
USE SCHEMA COMMON;


CREATE OR REPLACE TABLE DIM_CHANNEL (
  CHANNEL_ID       NUMBER AUTOINCREMENT PRIMARY KEY COMMENT 'SURROGATE KEY FOR CHANNEL',
  RAW_SOURCE       STRING COMMENT 'RAW TRAFFIC SOURCE FROM STAGING',
  CHANNEL_GROUP    STRING COMMENT 'NORMALIZED CHANNEL GROUP (PAID, ORGANIC, EMAIL, SOCIAL, DIRECT, OTHER)'
)
COMMENT = 'CHANNEL DIMENSION (CUSTOMER ACQUISITION / TRAFFIC SOURCE NORMALIZATION)';

-- LOAD: DISTINCT SOURCES FROM CUSTOMERS + EVENTS
INSERT OVERWRITE INTO DIM_CHANNEL (RAW_SOURCE, CHANNEL_GROUP)
SELECT DISTINCT
  TRAFFIC_SOURCE AS RAW_SOURCE,
  CASE
    WHEN UPPER(TRAFFIC_SOURCE) IN ('ADWORDS','SEARCH') THEN 'PAID_SEARCH'
    WHEN UPPER(TRAFFIC_SOURCE) = 'DISPLAY'             THEN 'DISPLAY'
    WHEN UPPER(TRAFFIC_SOURCE) IN ('FACEBOOK','YOUTUBE') THEN 'SOCIAL'
    WHEN UPPER(TRAFFIC_SOURCE) = 'EMAIL'               THEN 'EMAIL'
    WHEN UPPER(TRAFFIC_SOURCE) = 'ORGANIC'             THEN 'ORGANIC'
    ELSE 'OTHER'
  END AS CHANNEL_GROUP
FROM (
    SELECT TRAFFIC_SOURCE FROM &{ENV}_SILVER.STAGING.CUSTOMERS
    UNION
    SELECT TRAFFIC_SOURCE FROM &{ENV}_SILVER.STAGING.EVENTS
) T
WHERE TRAFFIC_SOURCE IS NOT NULL;
