!set variable_substitution=true;

-- Target context = SILVER/COMMON for the current ENV (DEV/QA/PROD)
USE DATABASE &{ENV}_SILVER;
USE SCHEMA COMMON;

CREATE OR REPLACE TABLE DIM_PRODUCT (
  PRODUCT_ID             NUMBER        PRIMARY KEY COMMENT 'BUSINESS KEY FROM STAGING.PRODUCTS',
  NAME                   STRING        COMMENT 'PRODUCT NAME',
  BRAND                  STRING        COMMENT 'PRODUCT BRAND',
  CATEGORY               STRING        COMMENT 'PRODUCT CATEGORY',
  DEPARTMENT             STRING        COMMENT 'PRODUCT DEPARTMENT',
  SKU                    STRING        COMMENT 'PRODUCT SKU',
  RETAIL_PRICE           NUMBER(18,2)  COMMENT 'STANDARD RETAIL PRICE',
  COST                   NUMBER(18,2)  COMMENT 'STANDARD UNIT COST',
  DISTRIBUTION_CENTER_ID NUMBER        COMMENT 'FK TO DIM_DISTRIBUTION_CENTER'
)
COMMENT = 'PRODUCT DIMENSION (ONE ROW PER PRODUCT, ATTRIBUTES FOR ANALYTICS)';

INSERT INTO DIM_PRODUCT
SELECT
  PRODUCT_ID,
  NAME,
  BRAND,
  CATEGORY,
  DEPARTMENT,
  SKU,
  RETAIL_PRICE,
  COST,
  DISTRIBUTION_CENTER_ID
FROM &{ENV}_SILVER.STAGING.PRODUCTS;