!set variable_substitution=true;

-- Target context = SILVER/COMMON for the current ENV (DEV/QA/PROD)
USE DATABASE &{ENV}_SILVER;
USE SCHEMA COMMON;

CREATE OR REPLACE TABLE DIM_GEOGRAPHY (
  GEO_ID       NUMBER AUTOINCREMENT PRIMARY KEY COMMENT 'Surrogate key for Geography',
  COUNTRY      STRING COMMENT 'It stores name of the country',
  STATE        STRING COMMENT 'it stores state or the region',
  CITY         STRING COMMENT 'It stores name of the city',
  POSTAL_CODE  STRING COMMENT 'It stores zip/postal code',
  LATITUDE     FLOAT  COMMENT 'It stores the latitude',
  LONGITUDE    FLOAT  COMMENT 'It stores the longitude'
)
COMMENT = 'It stores central geography lookup for customers, events, distribution centers';

-- LOAD: DERIVE UNIQUE COMBOS FROM CUSTOMERS + EVENTS + DISTRIBUTION CENTERS
INSERT INTO DIM_GEOGRAPHY (COUNTRY, STATE, CITY, POSTAL_CODE, LATITUDE, LONGITUDE)
SELECT DISTINCT
  COUNTRY,
  STATE,
  CITY,
  POSTAL_CODE,
  LATITUDE,
  LONGITUDE
FROM (
    SELECT COUNTRY, STATE, CITY, POSTAL_CODE, LATITUDE, LONGITUDE
    FROM &{ENV}_SILVER.STAGING.CUSTOMERS
    UNION
    SELECT NULL AS COUNTRY, STATE, CITY, POSTAL_CODE, NULL AS LATITUDE, NULL AS LONGITUDE
    FROM &{ENV}_SILVER.STAGING.EVENTS
    UNION
    SELECT NULL AS COUNTRY, NULL AS STATE, NAME AS CITY, NULL AS POSTAL_CODE, LATITUDE, LONGITUDE
    FROM &{ENV}_SILVER.STAGING.DISTRIBUTION_CENTERS
);
