!set variable_substitution=true;

-- Target context = SILVER/COMMON for the current ENV (DEV/QA/PROD)
USE DATABASE &{ENV}_SILVER;
USE SCHEMA COMMON;

CREATE OR REPLACE TABLE DIM_DISTRIBUTION_CENTER (
  DC_ID          NUMBER        PRIMARY KEY COMMENT 'BUSINESS KEY FROM STAGING.DISTRIBUTION_CENTERS',
  NAME           STRING        COMMENT 'NAME OF DISTRIBUTION CENTER',
  LATITUDE       FLOAT         COMMENT 'LATITUDE',
  LONGITUDE      FLOAT         COMMENT 'LONGITUDE',
  GEO_ID         NUMBER        COMMENT 'FK TO DIM_GEOGRAPHY (OPTIONAL LINKAGE)'
)
COMMENT = 'DISTRIBUTION CENTER DIMENSION (LOGISTICS ENTITIES)';

-- LOAD: DIRECT FROM STAGING
INSERT OVERWRITE INTO DIM_DISTRIBUTION_CENTER
SELECT
  DC_ID,
  NAME,
  LATITUDE,
  LONGITUDE,
  NULL AS GEO_ID   -- OPTIONALLY MAP VIA DIM_GEOGRAPHY LATER
FROM &{ENV}_SILVER.STAGING.DISTRIBUTION_CENTERS;

