!set variable_substitution=true;

-- Target context = SILVER/COMMON for the current ENV (DEV/QA/PROD)
USE DATABASE &{ENV}_SILVER;
USE SCHEMA COMMON;

CREATE OR REPLACE TABLE DIM_CUSTOMER (
  CUSTOMER_ID        NUMBER        PRIMARY KEY COMMENT 'BUSINESS KEY FROM STAGING.CUSTOMERS',
  FIRST_NAME         STRING        COMMENT 'CUSTOMER FIRST NAME',
  LAST_NAME          STRING        COMMENT 'CUSTOMER LAST NAME',
  EMAIL              STRING        COMMENT 'CUSTOMER EMAIL',
  AGE                NUMBER        COMMENT 'AGE IN YEARS',
  GENDER             STRING        COMMENT 'GENDER',
  STATE              STRING        COMMENT 'STATE / REGION',
  COUNTRY            STRING        COMMENT 'COUNTRY',
  CITY               STRING        COMMENT 'CITY',
  POSTAL_CODE        STRING        COMMENT 'ZIP/POSTAL CODE',
  LATITUDE           FLOAT         COMMENT 'CUSTOMER GEO LATITUDE',
  LONGITUDE          FLOAT         COMMENT 'CUSTOMER GEO LONGITUDE',
  TRAFFIC_SOURCE     STRING        COMMENT 'ORIGINAL ACQUISITION SOURCE',
  CREATED_AT         TIMESTAMP_NTZ COMMENT 'WHEN CUSTOMER WAS CREATED IN SOURCE'
)
COMMENT = 'CUSTOMER DIMENSION (ONE ROW PER CUSTOMER, ATTRIBUTES FOR ANALYTICS)';

INSERT OVERWRITE INTO DIM_CUSTOMER
SELECT
  CUSTOMER_ID,
  FIRST_NAME,
  LAST_NAME,
  EMAIL,
  AGE,
  GENDER,
  STATE,
  COUNTRY,
  CITY,
  POSTAL_CODE,
  LATITUDE,
  LONGITUDE,
  TRAFFIC_SOURCE,
  CREATED_AT
FROM &{ENV}_SILVER.STAGING.CUSTOMERS;
