!set variable_substitution=true;

-- Target context = SILVER/COMMON for the current ENV (DEV/QA/PROD)
USE DATABASE &{ENV}_SILVER;
USE SCHEMA COMMON;

CREATE OR REPLACE TABLE DIM_GEOGRAPHY (
  GEO_ID       NUMBER AUTOINCREMENT PRIMARY KEY COMMENT 'SURROGATE KEY FOR GEOGRAPHY',
  COUNTRY      STRING COMMENT 'COUNTRY NAME',
  STATE        STRING COMMENT 'STATE OR REGION',
  CITY         STRING COMMENT 'CITY NAME',
  POSTAL_CODE  STRING COMMENT 'ZIP/POSTAL CODE',
  LATITUDE     FLOAT  COMMENT 'LATITUDE',
  LONGITUDE    FLOAT  COMMENT 'LONGITUDE'
)
COMMENT = 'GEOGRAPHY DIMENSION (NORMALIZED LOCATION ATTRIBUTES)';

-- LOAD: DERIVE UNIQUE COMBOS FROM CUSTOMERS + EVENTS + DISTRIBUTION CENTERS
INSERT OVERWRITE INTO DIM_GEOGRAPHY (COUNTRY, STATE, CITY, POSTAL_CODE, LATITUDE, LONGITUDE)
SELECT DISTINCT
  COUNTRY,
  STATE,
  CITY,
  POSTAL_CODE,
  LATITUDE,
  LONGITUDE
FROM (
    SELECT COUNTRY, STATE, CITY, POSTAL_CODE, LATITUDE, LONGITUDE
    FROM &{ENV}_SILVER.STAGING.CUSTOMERS
    UNION
    SELECT NULL AS COUNTRY, STATE, CITY, POSTAL_CODE, NULL AS LATITUDE, NULL AS LONGITUDE
    FROM &{ENV}_SILVER.STAGING.EVENTS
    UNION
    SELECT NULL AS COUNTRY, NULL AS STATE, NAME AS CITY, NULL AS POSTAL_CODE, LATITUDE, LONGITUDE
    FROM &{ENV}_SILVER.STAGING.DISTRIBUTION_CENTERS
);
