!set variable_substitution=true;

-- Target context = SILVER/STAGING for the current ENV (DEV/QA/PROD)
USE DATABASE &{ENV}_SILVER;
USE SCHEMA STAGING;

CREATE OR REPLACE TABLE INVENTORY_ITEMS AS
SELECT
  ID::NUMBER AS INVENTORY_ITEM_ID,
  PRODUCT_ID::NUMBER AS PRODUCT_ID,
  CREATED_AT::TIMESTAMP_NTZ AS CREATED_AT,
  SOLD_AT::TIMESTAMP_NTZ AS SOLD_AT,
  COST::NUMBER(18,2) AS COST,
  PRODUCT_CATEGORY::VARCHAR AS PRODUCT_CATEGORY,
  PRODUCT_NAME::VARCHAR AS PRODUCT_NAME,
  PRODUCT_BRAND::VARCHAR AS PRODUCT_BRAND,
  PRODUCT_RETAIL_PRICE::NUMBER(18,2) AS PRODUCT_RETAIL_PRICE,
  PRODUCT_DEPARTMENT::VARCHAR AS PRODUCT_DEPARTMENT,
  PRODUCT_SKU::VARCHAR AS PRODUCT_SKU
FROM &{ENV}_BRONZE.RAW.INVENTORY_ITEMS;

-- Add the primary key constraint
ALTER TABLE INVENTORY_ITEMS ADD CONSTRAINT PK_INVENTORY_ITEMS PRIMARY KEY(INVENTORY_ITEM_ID);

-- Add a desription for the entire table
ALTER TABLE INVENTORY_ITEMS SET COMMENT = 'This table stores information about the inventory items and their details';

-- Add comments to each column
ALTER TABLE INVENTORY_ITEMS MODIFY COLUMN INVENTORY_ITEM_ID COMMENT 'It stores the unique inventory item ID';
ALTER TABLE INVENTORY_ITEMS MODIFY COLUMN PRODUCT_ID COMMENT 'It stores the unique product ID';
ALTER TABLE INVENTORY_ITEMS MODIFY COLUMN CREATED_AT COMMENT 'It stores the date and time when the item was created in the system';
ALTER TABLE INVENTORY_ITEMS MODIFY COLUMN SOLD_AT COMMENT 'It stores the date and time when the item was sold';
ALTER TABLE INVENTORY_ITEMS MODIFY COLUMN COST COMMENT 'It stores the cost of the item';
ALTER TABLE INVENTORY_ITEMS MODIFY COLUMN PRODUCT_CATEGORY COMMENT 'It stores the category of the product ';
ALTER TABLE INVENTORY_ITEMS MODIFY COLUMN PRODUCT_NAME COMMENT 'It stores the name of the product';
ALTER TABLE INVENTORY_ITEMS MODIFY COLUMN PRODUCT_BRAND COMMENT 'It stores the brand of the product';
ALTER TABLE INVENTORY_ITEMS MODIFY COLUMN PRODUCT_RETAIL_PRICE COMMENT 'It stores the retail price of the product';
ALTER TABLE INVENTORY_ITEMS MODIFY COLUMN PRODUCT_DEPARTMENT COMMENT 'It stores the department of the product';
ALTER TABLE INVENTORY_ITEMS MODIFY COLUMN PRODUCT_SKU COMMENT 'It stores the SKU of the product';
