!set variable_substitution=true;

-- Target context = SILVER/STAGING for the current ENV (DEV/QA/PROD)
USE DATABASE &{ENV}_SILVER;
USE SCHEMA STAGING;

CREATE OR REPLACE TABLE PRODUCTS AS
SELECT
  ID::NUMBER AS PRODUCT_ID,
  NAME::VARCHAR AS NAME,
  BRAND::VARCHAR AS BRAND,
  CATEGORY::VARCHAR AS CATEGORY,
  DEPARTMENT::VARCHAR AS DEPARTMENT,
  SKU::VARCHAR AS SKU,
  RETAIL_PRICE::NUMBER(18,2) AS RETAIL_PRICE,
  COST::NUMBER(18,2) AS COST,
  DISTRIBUTION_CENTER_ID::NUMBER AS DISTRIBUTION_CENTER_ID
FROM &{ENV}_BRONZE.RAW.PRODUCTS;

-- Add the primary key constraint
ALTER TABLE PRODUCTS ADD CONSTRAINT PK_PRODUCTS PRIMARY KEY(PRODUCT_ID);

-- Add a desription for the entire table
ALTER TABLE PRODUCTS SET COMMENT = 'This table stores information about the product details';

-- Add comments to each column
ALTER TABLE PRODUCTS MODIFY COLUMN PRODUCT_ID COMMENT 'It stores unique product ID';
ALTER TABLE PRODUCTS MODIFY COLUMN NAME COMMENT 'It stores name of the product';
ALTER TABLE PRODUCTS MODIFY COLUMN BRAND COMMENT 'It stores Brand of the product';
ALTER TABLE PRODUCTS MODIFY COLUMN CATEGORY COMMENT 'It stores category of the product';
ALTER TABLE PRODUCTS MODIFY COLUMN DEPARTMENT COMMENT 'It stores department of the productE Eg. Women/Men/Kids';
ALTER TABLE PRODUCTS MODIFY COLUMN SKU COMMENT 'It stores SKU of the product';
ALTER TABLE PRODUCTS MODIFY COLUMN RETAIL_PRICE COMMENT 'It stores Retail Price of the product';
ALTER TABLE PRODUCTS MODIFY COLUMN COST COMMENT 'It stores cost of the product';
ALTER TABLE PRODUCTS MODIFY COLUMN DISTRIBUTION_CENTER_ID COMMENT 'It stores distribution center id of the product';

