!set variable_substitution=true;

-- Target context = SILVER/STAGING for the current ENV (DEV/QA/PROD)
USE DATABASE &{ENV}_SILVER;
USE SCHEMA STAGING;

CREATE OR REPLACE TABLE EVENTS AS
SELECT
  ID::NUMBER AS EVENT_ID,
  USER_ID::NUMBER AS CUSTOMER_ID,
  SEQUENCE::NUMBER(18,0) AS SEQUENCE,
  SESSION_ID::VARCHAR AS SESSION_ID,
  CREATED_AT::TIMESTAMP_NTZ AS CREATED_AT,
  IP_ADDRESS::VARCHAR AS IP_ADDRESS,
  CITY::VARCHAR AS CITY,
  STATE::VARCHAR AS STATE,
  POSTAL_CODE::VARCHAR AS POSTAL_CODE,
  BROWSER::VARCHAR AS BROWSER,
  TRAFFIC_SOURCE::VARCHAR AS TRAFFIC_SOURCE,
  URI::VARCHAR AS URI,
  EVENT_TYPE::VARCHAR AS EVENT_TYPE
FROM &{ENV}_BRONZE.RAW.EVENTS;

-- Add the primary key constraint
ALTER TABLE EVENTS ADD CONSTRAINT PK_EVENTS PRIMARY KEY(EVENT_ID);

-- Add a desription for the entire table
ALTER TABLE EVENTS SET COMMENT = 'This table stores information about the events like browsing through the website.';

-- Add comments to each column
ALTER TABLE EVENTS MODIFY COLUMN EVENT_ID COMMENT 'It stores the unique event ID';
ALTER TABLE EVENTS MODIFY COLUMN CUSTOMER_ID COMMENT 'It stores the unique customer ID';
ALTER TABLE EVENTS MODIFY COLUMN SEQUENCE COMMENT 'It stores the sequence number of the event';
ALTER TABLE EVENTS MODIFY COLUMN SESSION_ID COMMENT 'It stores the session ID of the event';
ALTER TABLE EVENTS MODIFY COLUMN CREATED_AT COMMENT 'It stores the date and time when the event was created';
ALTER TABLE EVENTS MODIFY COLUMN IP_ADDRESS COMMENT 'It stores the IP address of the event';
ALTER TABLE EVENTS MODIFY COLUMN CITY COMMENT 'It stores the city of the event';
ALTER TABLE EVENTS MODIFY COLUMN STATE COMMENT 'It stores the state of the event';
ALTER TABLE EVENTS MODIFY COLUMN POSTAL_CODE COMMENT 'It stores the postal code of the event';
ALTER TABLE EVENTS MODIFY COLUMN BROWSER COMMENT 'It stores the browser used for the event';
ALTER TABLE EVENTS MODIFY COLUMN TRAFFIC_SOURCE COMMENT 'It stores the traffic source of the event';
ALTER TABLE EVENTS MODIFY COLUMN URI COMMENT 'It stores the URI of the event';
ALTER TABLE EVENTS MODIFY COLUMN EVENT_TYPE COMMENT 'It stores the type of the event';