!set variable_substitution=true;

-- Target context = SILVER/STAGING for the current ENV (DEV/QA/PROD)
USE DATABASE &{ENV}_SILVER;
USE SCHEMA STAGING;

CREATE OR REPLACE TABLE CUSTOMERS AS
SELECT
  ID::NUMBER AS CUSTOMER_ID,
  FIRST_NAME::VARCHAR AS FIRST_NAME,
  LAST_NAME::VARCHAR AS LAST_NAME,
  EMAIL::VARCHAR AS EMAIL,
  AGE::NUMBER(9,0) AS AGE,
  GENDER::VARCHAR AS GENDER,
  CITY::VARCHAR AS CITY,
  STATE::VARCHAR AS STATE,
  POSTAL_CODE::VARCHAR AS POSTAL_CODE,
  COUNTRY::VARCHAR AS COUNTRY,
  LATITUDE::FLOAT AS LATITUDE,
  LONGITUDE::FLOAT AS LONGITUDE,
  TRAFFIC_SOURCE::VARCHAR AS TRAFFIC_SOURCE,
  CREATED_AT::TIMESTAMP_NTZ AS CREATED_AT
FROM &{ENV}_BRONZE.RAW.USERS;


-- Add the primary key constraint
ALTER TABLE CUSTOMERS ADD CONSTRAINT PK_CUSTOMERS PRIMARY KEY(CUSTOMER_ID);

-- Add a desription for the entire table
ALTER TABLE CUSTOMERS SET COMMENT = 'This table stores information about all customers.';

-- Add desription to each column
ALTER TABLE CUSTOMERS MODIFY COLUMN CUSTOMER_ID COMMENT 'It stores the unique customer ID';
ALTER TABLE CUSTOMERS MODIFY COLUMN FIRST_NAME COMMENT 'It stores the first name of the customer';
ALTER TABLE CUSTOMERS MODIFY COLUMN LAST_NAME COMMENT 'It stores the last name of the customer';
ALTER TABLE CUSTOMERS MODIFY COLUMN EMAIL COMMENT 'It stores the email address of the customer';
ALTER TABLE CUSTOMERS MODIFY COLUMN AGE COMMENT 'It stores the age of the customer';
ALTER TABLE CUSTOMERS MODIFY COLUMN GENDER COMMENT 'It stores the gender of the customer';
ALTER TABLE CUSTOMERS MODIFY COLUMN CITY COMMENT 'It stores the city of the customer';
ALTER TABLE CUSTOMERS MODIFY COLUMN STATE COMMENT 'It stores the state of the customer';
ALTER TABLE CUSTOMERS MODIFY COLUMN POSTAL_CODE COMMENT 'It stores the postal code of the location of customer';
ALTER TABLE CUSTOMERS MODIFY COLUMN COUNTRY COMMENT 'It stores the country of the customer';
ALTER TABLE CUSTOMERS MODIFY COLUMN LATITUDE COMMENT 'It stores the latitude of the customer''s location';
ALTER TABLE CUSTOMERS MODIFY COLUMN LONGITUDE COMMENT 'It stores the longitude of the customer''s location';
ALTER TABLE CUSTOMERS MODIFY COLUMN TRAFFIC_SOURCE COMMENT 'It stores the source of the customer''s traffic';
ALTER TABLE CUSTOMERS MODIFY COLUMN CREATED_AT COMMENT 'It stores the date and time when the customer was created';