!set variable_substitution=true;

-- Target context = SILVER/STAGING for the current ENV (DEV/QA/PROD)
USE DATABASE &{ENV}_SILVER;
USE SCHEMA STAGING;

CREATE OR REPLACE TABLE DISTRIBUTION_CENTERS AS
SELECT
  ID::NUMBER AS DC_ID,
  NAME::VARCHAR AS NAME,
  LATTITUDE::FLOAT AS LATITUDE,
  LONGITUDE::FLOAT AS LONGITUDE
FROM &{ENV}_BRONZE.RAW.DISTRIBUTION_CENTERS;


-- Add the primary key constraint
ALTER TABLE DISTRIBUTION_CENTERS ADD CONSTRAINT PK_DISTRIBUTION_CENTERS PRIMARY KEY(DC_ID);

-- Add a desription for the entire table
ALTER TABLE DISTRIBUTION_CENTERS SET COMMENT = 'This table stores information about the Distribution centers.';

-- Add comments to each column
ALTER TABLE DISTRIBUTION_CENTERS MODIFY COLUMN DC_ID COMMENT 'It stores distribution center ID';
ALTER TABLE DISTRIBUTION_CENTERS MODIFY COLUMN NAME COMMENT 'It stores name of distribution center';
ALTER TABLE DISTRIBUTION_CENTERS MODIFY COLUMN LATITUDE COMMENT 'It stores Latitude of distribution center';
ALTER TABLE DISTRIBUTION_CENTERS MODIFY COLUMN LONGITUDE COMMENT 'It stores Longitude of distribution center';