name: Provision Plan

on:
  pull_request:
    branches: [ qa, main ]
    paths:
      - 'provision/**'
      - 'sql_files/**'
      - 'snowsql/**'
      - 'toolkit.conf'
      - '.github/workflows/**'

jobs:
  lint:
    name: Lint Workflows
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install actionlint
        run: |
          curl -sSfL https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash -o /tmp/download-actionlint.bash
          bash /tmp/download-actionlint.bash latest /usr/local/bin
      - name: Run actionlint
        run: actionlint -color

  plan:
    name: Snowflake Plan
    runs-on: ubuntu-latest
    needs: lint
    env:
      ENV: ${{ github.base_ref == 'qa' && 'QA' || 'PROD' }}
      SNOWFLAKE_ACCOUNT:   ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
      SNOWFLAKE_USER:      ${{ github.base_ref == 'qa' && secrets.SNOWFLAKE_USER_QA   || secrets.SNOWFLAKE_USER_PROD }}
      SNOWFLAKE_PASSWORD:  ${{ github.base_ref == 'qa' && secrets.SNOWFLAKE_PASSWORD_QA || secrets.SNOWFLAKE_PASSWORD_PROD }}
      SNOWFLAKE_ROLE:      ${{ github.base_ref == 'qa' && secrets.SNOWFLAKE_ROLE_QA   || secrets.SNOWFLAKE_ROLE_PROD }}
      SNOWSQL_PWD:         ${{ github.base_ref == 'qa' && secrets.SNOWFLAKE_PASSWORD_QA || secrets.SNOWFLAKE_PASSWORD_PROD }}
      SNOWFLAKE_AUTHENTICATOR: "snowflake"
      TOOLKIT_AUTH_TOKEN: ${{ secrets.TOOLKIT_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 17 (Toolkit requires Java)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install phData Toolkit CLI
        env:
          TOOLKIT_VERSION: "0.79.0"
          TOOLKIT_URL: "https://repo.phdata.io/3BCJzuXgtfTCoa6c/toolkit-cli/maven/io/phdata/toolkit/toolkit-cli/0.79.0/toolkit-cli-0.79.0.zip"
        shell: bash
        run: |
          set -euo pipefail
          ROOT="$HOME/.phdata/toolkit-${TOOLKIT_VERSION}"
          mkdir -p "$ROOT"
          printf 'Downloading Toolkit: %s\n' "$TOOLKIT_URL"
          curl -sSfL "$TOOLKIT_URL" -o "/tmp/toolkit-${TOOLKIT_VERSION}.zip"
          unzip -q "/tmp/toolkit-${TOOLKIT_VERSION}.zip" -d "$ROOT"

          # Look for the 'toolkit' launcher script, even if not executable yet
          BIN_PATH="$(find "$ROOT" -maxdepth 2 -type f -name toolkit | head -n1 || true)"
          if [ -n "$BIN_PATH" ]; then
          chmod +x "$BIN_PATH"
          DIRNAME="$(dirname "$BIN_PATH")"
          echo "$DIRNAME" >> "$GITHUB_PATH"
          export PATH="$DIRNAME:$PATH"
          else
            echo "Could not find 'toolkit' launcher script in extracted archive. Contents:"
            find "$ROOT" -maxdepth 2 -print
            exit 1
          fi

          WHICH_TOOLKIT="$(command -v toolkit || true)"
          if [ -n "$WHICH_TOOLKIT" ]; then
            printf 'Toolkit on PATH: %s\n' "$WHICH_TOOLKIT"
          else
            echo "Toolkit not found on PATH (unexpected)"; exit 1
          fi
          toolkit --version || true

      - name: Provision (plan only)
        run: toolkit provision apply --plan --conf authToken="$TOOLKIT_TOKEN"

      - name: List changed SQL files (informational)
        shell: bash
        run: |
          set -euo pipefail
          BASE_SHA="${{ github.event.pull_request.base.sha }}"
          HEAD_SHA="${{ github.event.pull_request.head.sha }}"
          git diff --name-only "$BASE_SHA" "$HEAD_SHA" | grep -E '^sql_files/.*\.sql$' || echo "No SQL changes."

      - name: Install SnowSQL CLI (pre-check)
        shell: bash
        run: |
          set -euo pipefail
          SNOWSQL_VERSION="1.2.31"
          PKG="snowsql-${SNOWSQL_VERSION}-linux_x86_64.bash"
          curl -sSfL "https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/${SNOWSQL_VERSION}/${PKG}" -o "/tmp/${PKG}"
          bash "/tmp/${PKG}" -b -p "$HOME/.local/snowsql"
          echo "$HOME/.local/snowsql/bin" >> "$GITHUB_PATH"
          snowsql -v

      - name: Snowflake connectivity smoke test (no changes)
        shell: bash
        run: |
          set -euo pipefail
          # Quick “can we connect?” check—no DDL, no changes.
          SNOWSQL_PWD="$SNOWSQL_PWD" snowsql \
            -a "$SNOWFLAKE_ACCOUNT" \
            -u "$SNOWFLAKE_USER" \
            -w "$SNOWFLAKE_WAREHOUSE" \
            -r "$SNOWFLAKE_ROLE" \
            -DENV="${ENV}" \
            -o exit_on_error=true -o friendly=false \
            -q "SELECT CURRENT_ACCOUNT(), CURRENT_ROLE(), CURRENT_WAREHOUSE();"



